// -----------------------------------------------------------------------------
// <copyright file="SurrogateId.cs" company="Alma.DiscordBot.Api.Core.Abstractions">
//   Copyright (c) Alma.DiscordBot.Api.Core.Abstractions All rights reserved.
// </copyright>
// <author>$author$</author>
// <created>11/03/2026 16:32:18</created>
// -----------------------------------------------------------------------------

namespace Alma.DiscordBot.Api.Core.Abstractions.ValueObjects
{
    /// <summary>
    /// Represents a technical 32-bit identifier used during persistence.
    /// </summary>
    /// <remarks>
    /// A Surrogate identifier is guaranteed to be strictly positive and non-zero.
    /// <para>
    /// <see cref="SurrogateId"/> wraps a <see cref="int"/> value generated by
    /// the persistence layer. Values less than or equal to zero are considered
    /// invalid and will cause an <see cref="ArgumentException"/> to be thrown
    /// at instantiation.
    /// </para>
    /// </remarks>
    /// <example>
    /// Creating a SurrogateId from a 32-bit integer:
    /// <code>
    /// var entityId = new SurrogateId(1);
    /// int raw = entityId; // implicit conversion
    /// </code>
    /// </example>
    /// <seealso cref="IId"/>
    /// <seealso cref="Snowflake"/>
    /// <seealso cref="Uuid"/>
    public readonly struct SurrogateId : IId, IEquatable<SurrogateId>
    {
        // -------------------------------------------------------------------------
        // Constructor
        // -------------------------------------------------------------------------

        /// <summary>
        /// Initializes a new instance of the <see cref="SurrogateId"/> struct
        /// with the specified raw value.
        /// </summary>
        /// <param name="value">
        /// The raw 32-bit integer value to wrap. Must be strictly positive.
        /// </param>
        /// <exception cref="ArgumentException">
        /// Thrown when <paramref name="value"/> is zero or negative.
        /// </exception>
        public SurrogateId(int value)
        {
            if (value <= 0)
            {
                throw new ArgumentException(ErrorMessages.ID_BELLOW_ZERO_ERROR_MESSAGE, nameof(value));
            }

            Value = value;
        }

        // -------------------------------------------------------------------------
        // Properties
        // -------------------------------------------------------------------------

        /// <summary>
        /// Gets the raw 32-bit value of this <see cref="SurrogateId"/> identifier.
        /// </summary>
        /// <value>
        /// A strictly positive <see cref="int"/> representing the persistence-assigned
        /// identifier.
        /// </value>
        public int Value { get; }

        // -------------------------------------------------------------------------
        // Equality
        // -------------------------------------------------------------------------

        /// <summary>
        /// Determines whether the current <see cref="SurrogateId"/> is equal
        /// to another <see cref="SurrogateId"/>.
        /// </summary>
        /// <param name="other">
        /// The <see cref="SurrogateId"/> to compare with the current instance.
        /// </param>
        /// <returns>
        /// <see langword="true"/> if both instances share the same value;
        /// otherwise <see langword="false"/>.
        /// </returns>
        public bool Equals(SurrogateId other) => Value == other.Value;

        /// <inheritdoc/>
        public override bool Equals(object? obj) =>
            obj is SurrogateId other && Equals(other);

        /// <inheritdoc/>
        public override int GetHashCode() => Value.GetHashCode();

        /// <inheritdoc/>
        public override string ToString() => Value.ToString();

        // -------------------------------------------------------------------------
        // Operators
        // -------------------------------------------------------------------------

        /// <summary>
        /// Determines whether two <see cref="SurrogateId"/> instances are equal.
        /// </summary>
        /// <param name="left">The left operand.</param>
        /// <param name="right">The right operand.</param>
        /// <returns>
        /// <see langword="true"/> if both instances are equal;
        /// otherwise <see langword="false"/>.
        /// </returns>
        public static bool operator ==(SurrogateId left, SurrogateId right) =>
            left.Equals(right);

        /// <summary>
        /// Determines whether two <see cref="SurrogateId"/> instances are not equal.
        /// </summary>
        /// <param name="left">The left operand.</param>
        /// <param name="right">The right operand.</param>
        /// <returns>
        /// <see langword="true"/> if both instances differ;
        /// otherwise <see langword="false"/>.
        /// </returns>
        public static bool operator !=(SurrogateId left, SurrogateId right) =>
            !left.Equals(right);

        /// <summary>
        /// Implicitly converts a <see cref="SurrogateId"/> to its raw value.
        /// </summary>
        /// <param name="obj">The <see cref="SurrogateId"/> to convert.</param>
        /// <returns>The raw underlying value.</returns>
        public static implicit operator int(SurrogateId obj) => obj.Value;

        /// <summary>
        /// Explicitly converts a raw value to a <see cref="SurrogateId"/>.
        /// </summary>
        /// <param name="value">
        /// The raw value to convert. Must satisfy the validation constraints.
        /// </param>
        /// <returns>A new <see cref="SurrogateId"/> wrapping the provided value.</returns>
        /// <exception cref="ArgumentException">
        /// Thrown when <paramref name="value"/> is zero or negative.
        /// </exception>
        public static explicit operator SurrogateId(int value) => new(value);

        // -------------------------------------------------------------------------
        // Messages
        // -------------------------------------------------------------------------

        /// <summary>
        /// Provides error messages for <see cref="SurrogateId"/> validation failures.
        /// </summary>
        private static class ErrorMessages
        {
            internal const string ID_BELLOW_ZERO_ERROR_MESSAGE = "Surrogate Id value must be greater than zero.";
        }
    }
}
